name: GitHub Pages

on:
  push:
    branches:
      - blog-poison  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # default: public
          publish_branch: gh-pages ## default: gh-pages
          destination_dir: / # 目标目录
          force_orphan: true # 允许您仅使用最新提交创建发布分支
          # cname: github.com
          allow_empty_commit: true # ⭐️ 允许空提交
          commit_message: ${{ github.event.head_commit.message }} # 设置自定义提交消息
