name: GitHub Pages

on:
  push:
    branches:
      - blog-poison  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/pages-poison'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public