# This is a basic workflow to help you get started with Actions
name: Github-Pages

on: # 触发条件
  push: # push 
    branches:  # 分支名称
      - blog-poison

jobs:
  blog_jobs:
    name: build to blog
    runs-on: ubuntu-20.04 # 设置运行环境
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    # 要执行的步骤
    steps:
      # - uses: actions/checkout@v2
      #   with:
      #     submodules: true

      - name: Setup Hugo  # 安装 hugo
        uses: peaceiris/actions-hugo@v2
        with:
          # hugo-version: '0.85.0'
          # hugo-version: 'latest'
          hugo-version: '0.119.0'
          extended: false

      - name: Build # 编译站点
        run: |
          ls -l
          hugo --gc --minify --cleanDestinationDir --config hugo.toml # 自己寫執行的步驟
        # run: hugo --gc --minify --cleanDestinationDir --baseURL="https://www.sgfoot.com/"

      - name: copy file # 复制CNAME文件，用于绑定域名
        run: |
          # cp -f CNAME ./public
          cp README.md ./public
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: pages-poison
          force_orphan: true